config:
  source_plugin_dir: '~/.config/checker/plugins/source' # Optional, defaults to ~/.config/checker/plugins/source
  destination_plugin_dir: '~/.config/checker/plugins/destination' # Optional, defaults to ~/.config/checker/plugins/destination
  sources:
    github:
      interval: 3600 # Optional, default 60 minutes (3600 seconds)
      items:
        - 'tus/tusd'
        - 'gotenberg/gotenberg'
      destinations: [pushover] # Optional, by default notify all configured destinations
  destinations:
    pushover:
      token: 'your-pushover-token'
      user_key: 'your-user-key'
      device: 'iphone' # Optional
