name: Lint and test

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install
      - name: Lint code
        run: deno lint
      - name: Run test suite
        run: deno test
